config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :events
  get '/events/:id/edit', to: 'events#edit'

  resources :organiser
  get '/account', to: 'organiser#show'
  get '/login', to: 'organiser#login'
  post '/login', to: 'organiser#verify'
  get '/logout', to: 'organiser#logout'
  post '/like/', to: 'likes#like'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/components/_eventPartial.html.erb
<div class="event-image-container">

    <% if form %>
        <%= form.file_field :image, {hidden: :true} %>
        <%= form.label :image, (image_tag url_for(@event.image_url), {:class => 'event-image'}) %>
    <% else %>
        <%= image_tag url_for(@event.image_url), {:class => 'event-image'} %>
    <% end %>

    <% if form %>
        <%= form.text_field :name, {:class => 'form-control col-lg-2', :placeholder => 'Event Name'} %>
    <% else %>
        <h1><%= @event.name %></h1>
        <p id="like-count">Likes: <%= @event.likes %></p>
        <% if !event_owner(@event) %>
            <% if logged_in? %>
                <%= form_with scope: :like, url: like_path, remote: true do |form| %>
                    <%= form.hidden_field :event_id, value: @event.id %>
                    <input name="commit" value="<%= @liked ? 'Unlike' : 'Like' %>" class="btn btn-outline-secondary"
                           id="like-button" type="submit">
                <% end %>
            <% end %>
        <% else %>
            <%= link_to 'Edit', edit_event_path, {:class => 'btn btn-outline-secondary'} %>
        <% end %>
    <% end %>
</div>
<hr/>
<div class="row">
    <div class="col-lg-6">
        <h1>Description</h1>
        <% if form %>
            <%= form.cktext_area :description %>
        <% else %>
            <%= sanitize @event.description, tags: %w(strong em a b p img), attributes: %w(href style src) %>
        <% end %>
    </div>
    <div class="col-lg-6">
        <div class="row">
            <div class="col-lg-12">
                <h1>Category</h1>
                <% if form %>
                    <%= form.select :category, [ 'Other', 'Sport', 'Culture'], {}, {:class => 'form-control col-lg-5'} %>
                <% else %>
                    <%= @event.category %>
                <% end %>
            </div>
            <div class="col-lg-12">
                <h1>Organiser</h1>
                <% if form %>
                    <%= current_user.name %>
                <% else %>
                    <a href="mailto:<%= @event.organiser.email %>"><%= @event.organiser.name %></a>
                <% end %>
            </div>
            <div class="col-lg-12">
                <h1>Venue</h1>
                <% if form %>
                    <%= form.text_field :venue, {:class => 'form-control col-lg-5', :placeholder => 'Event Venue'} %>
                    <br/>
                <% else %>
                    <%= @event.venue %>
                <% end %>
            </div>
            <div class="col-lg-12">
                <h1>Date</h1>
                <% if form %>
                    <div class="input-group">
                        <%= form.date_field :day, {:class => 'form-control col-lg-4'} %><br/>
                        <span class="input-group-append">
                             <%= form.time_field :time, {:class => 'form-control',
                                                         :value => (@event.time ? @event.time.strftime('%H:%M'):'')} %>
                            <br/>
                        </span>
                    </div>
                <% else %>
                    <%= @event.readable_date %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<% if form %>
    <div>
        <%= form.collection_check_boxes :related_event, Event.all, :id, :name do |b| %>
            <%= b.check_box(class: 'related-box',
                            checked: (  @event.related_to?(b.object.id) && @event.not_new? ? 'checked' : 'false' )) %>
            <%= b.label(class: 'related-label') %>
            <br/>
        <% end %>
    </div>
<% end %>

app/views/layouts/components/_eventShort.html.erb
<% if eventsList.empty? %>
    <h2>No events could be found!</h2>
<% else %>
    <% if include_heading %>
        <%= render partial: 'layouts/components/eventheading', locals: {order_by: 'name'} %>
    <% end %>
    <% eventsList.each do |event| %>
        <hr/>
        <div class="row">
            <div class="col-lg-4 event-image-container">
                <a href="<%= event_path(event.id) %>">
                    <%= image_tag url_for(event.image_url), {:class => 'event-preview'} %>
                </a>
                <a href="<%= event_path(event.id) %>">
                    <h3><%= event.name %></h3>
                </a>
                <p>Category: <%= event.category %></p>
            </div>
            <div class="col-lg-8">
                <div>
                    <h4>Description</h4>
                    <div id="event-description">
                        <%= sanitize event.short_description %>
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-lg-6">
                        <div><h5>Organiser</h5><span>
                            <%= event_owner(event) ? 'Me' : event.organiser.name %>
                        </span></div>
                        <hr/>
                        <div><h5>When</h5><span><%= event.readable_date %></span></div>
                    </div>
                    <div class="col-lg-6">
                        <div><h5>Where</h5><span><%= event.venue %></span></div>
                        <hr/>
                        <div><h5>Likes</h5><span><%= event.likes %></span></div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/layouts/components/_eventheading.html.erb
<div class="row" id="sort-headings">
    <h4 class="col-lg-2">
        <a href="#">Name
            <% if order_by == 'name' %>
                <%= fa_icon 'angle-down' %>
            <% end %>
        </a>
    </h4>
    <h4 class="col-lg-2">
        <a href="#">Category</a>
        <% if order_by == 'category' %>
            <%= fa_icon 'angle-down' %>
        <% end %>
    </h4>
    <h4 class="col-lg-2">
        <a href="#">Organiser</a>
        <% if order_by == 'organiser' %>
            <%= fa_icon 'angle-down' %>
        <% end %>
    </h4>
    <h4 class="col-lg-2">
        <a href="#">When</a>
        <% if order_by == 'date' %>
            <%= fa_icon 'angle-down' %>
        <% end %>
    </h4>
    <h4 class="col-lg-2">
        <a href="#">Where</a>
        <% if order_by == 'venue' %>
            <%= fa_icon 'angle-down' %>
        <% end %>
    </h4>
    <h4 class="col-lg-2">
        <a href="#">Likes</a>
        <% if order_by == 'likes' %>
            <%= fa_icon 'angle-down' %>
        <% end %>
    </h4>
</div>

app/views/layouts/components/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to image_tag('logo.svg', :class => 'brand-image', :id => "nav-image"), root_path %>
    <img class="navbar-brand" href="/" />
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= @page =~ /home/i ? 'active' : '' %>">
                <%= link_to 'Home', root_path, {:class => 'nav-link'}%>
            </li>
            <li class="nav-item dropdown <%= @page =~ /event/i ? 'active' : '' %>">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Events
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'Search', events_path, {:class => 'dropdown-item'}%>
                    <a class="dropdown-item" href="#">Most Liked</a>
                    <a class="dropdown-item" href="#">Upcoming</a>
                    <%= link_to 'Create Event', new_event_path, {:class => 'dropdown-item'}%>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item  <%= @page =~ /user/i ? 'active' : '' %> <%= logged_in? ? 'dropdown' : '' %>">
                <% if logged_in? %>
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <%= fa_icon 'user-circle' %>
                        <%= current_user.name %>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <%= link_to 'My Account', organiser_path(current_user.id), {:class => 'dropdown-item'}%>
                        <%= link_to 'Logout', logout_path, {:class => 'dropdown-item'}%>
                    </div>
                <% else %>
                    <%= link_to 'Login/Register', login_path, {:class => 'nav-link'} %>
                <% end %>
            </li>
        </ul>
    </div>
</nav>