config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :events
  get '/events/:id/edit', to: 'events#edit'

  resources :organiser
  get '/account', to: 'organiser#show'
  get '/login', to: 'organiser#login'
  post '/login', to: 'organiser#verify'
  get '/logout', to: 'organiser#logout'
  post '/like/', to: 'likes#like'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organiser.rb
class Organiser < ApplicationRecord
  has_many :events
  validates :name, presence: true
  validates :email, presence: true, confirmation: true
  validates :password, presence: true, confirmation: true

  before_save :hash_password

  def name_posses
    name[-1] == 's' ? uc_name + '\'' : uc_name + '\'s'
  end

  def uc_name
    name.upcase_first
  end

  def password_correct?(pass)
    true if password == Digest::SHA1.hexdigest(salt + pass)
  end

  def hash_password
    self.salt = SecureRandom.base64(8)
    self.password = Digest::SHA1.hexdigest(salt + password)
  end
end

app/controllers/organiser_controller.rb
# frozen_string_literal: true

require 'digest/sha1'
class OrganiserController < ApplicationController
  def show
    @organiser = Organiser.find(params[:id])
    @page = "User|#{@organiser.uc_name}"
  end

  def login
    @page = 'User|Login'
    redirect_to current_user if logged_in?
  end

  def logout
    reset_session
    redirect_to root_path
  end

  def verify
    user = Organiser.find_by_email(params[:session][:email])
    if user&.password_correct?(params[:session][:password])
      start_session user
      redirect_to user
    else
      render 'login'
    end
  end

  def index
    @page = 'User|Home'
    @organisers = Organiser.all
  end

  def new
    @page = 'User|Register'
    @user = Organiser.new
  end

  def create
    @page = 'User|Register'
    @user = Organiser.new(organiser_params)
    if @user.save
      start_session @user
      redirect_to @user
    else
      redirect_to '/organiser/new', flash: { error: @user.errors.full_messages }
    end
  end

  def organiser_params
    params.require(:organiser).permit(:name, :email, :email_confirmation, :password, :password_confirmation)
  end
end

app/helpers/organiser_helper.rb
module OrganiserHelper
end

app/views/organiser/index.html.erb
<h1>Organisers</h1>
<p>Here's a list of organisers, why? Because the resource macro in my routes file made one,
    so I'm damn well gonna use it</p>
<div class="row">
    <div class="col-lg-4">
        <span><u>Name</u></span>
    </div>
    <div class="col-lg-4">
        <span><u>Events</u></span>
    </div>
    <div class="col-lg-4">
        <span><u>Email</u></span>
    </div>
</div>
<div class="row">
    <% @organisers.each do |organiser| %>
        <div class="col-lg-4">
            <%= link_to organiser.name, organiser%>
        </div>
        <div class="col-lg-4">
            <%= organiser.events.count %>
        </div>
        <div class="col-lg-4">
            <%= organiser.email %>
        </div>
    <% end %>
</div>

app/views/organiser/login.html.erb
<h1>Login</h1>
<div class="row justify-content-center">
<%= form_for(:session, url: login_path) do |form| %>
    <p>
        <%= form.label :email, {:class => 'col-form-label'} %><br/>
        <%= form.email_field :email, {:class => 'form-control'} %><br/>
        <%= form.label :password, {:class => 'col-form-label'} %><br/>
        <%= form.password_field :password, {:class => 'form-control'} %><br/>
        <%= form.submit 'Login', {:class => 'btn btn-outline-secondary'} %>
    </p>
<% end %>
</div>
<h2>No Account? No Problem!</h2>
<div class="row justify-content-center">
    <%= link_to 'register now!', new_organiser_path, {:class => 'btn btn-outline-success'} %>
</div>

app/views/organiser/new.html.erb
<h1>Register for RubyEvents</h1>
<%= form_with scope: :organiser, url: organiser_index_path, local: true do |form| %>
    <% if flash[:error] %>
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Failed to create account</h4>
            <p><%= pluralize(flash[:error].count, 'error') %> occurred while creating your account</p>
            <ul>
                <% flash[:error].each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
            <hr>
            <p class="mb-0">Please try again</p>
        </div>
    <% end %>
    <p>
        <%= form.label :name, {:class => 'col-form-label'} %><br/>
        <%= form.text_field :name, {:class => 'form-control col-lg-3'}%><br/>
    </p>
    <p>
        <%= form.label :email, {:class => 'col-form-label'}  %><br/>
        <%= form.email_field :email, {:class => 'form-control col-lg-3'} %><br/>
        <%= form.email_field :email_confirmation, {:class => 'form-control col-lg-3'} %><br/>
    </p>
    <p>
        <%= form.label :password, {:class => 'col-form-label'}  %><br/>
        <%= form.password_field :password, {:class => 'form-control col-lg-3'} %><br/>
        <%= form.password_field :password_confirmation, {:class => 'form-control col-lg-3'} %><br/>
    </p>
    <p>
        <%= form.submit 'Create Account', {:class => 'btn btn-outline-secondary' } %>
    </p>
<% end %>

app/views/organiser/show.html.erb
<% if current_user.id == @organiser.id %>
    <h1>My Account</h1>
    <p>Welcome to your page, <%= @organiser.uc_name %></p>
    <p>Here you can see all your events, make a new event and manage your profile. Make yourself at home!</p>
<% else %>
    <h1><%= @organiser.name_posses %> Page</h1>
    <br>
    <h3>Contact Details</h3>
    <p><%= @organiser.email %></p>
<% end %>

<h1><%= current_user.id == @organiser.id ? 'My' : @organiser.name_posses %> Events</h1>
<%= render partial: 'layouts/components/eventShort', locals: {eventsList: @organiser.events, include_heading: true} %>